name: Update Description and Topics

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set repository description and topics
      uses: actions/github-script@v6
      with:
        script: |
          const result = await github.repos.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            description: "Cool standart red theme",
            topics: ["homeassistant", "redtheme", "ui"]
          });
          console.log(result);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
