name: Update Description and Topics

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set repository description and topics
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const response = await github.repos.update({
            owner: owner,
            repo: repo,
            description: "Cool standart theme for ha",
            topics: ["homeassistant", "theme", "red"]
          });
          console.log(response);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
